export const LOGIN_PAGE_PATH = '/login'
export const REGISTER_PAGE_PATH = '/registration'
export const HOME_PAGE_PATH = '/'
export const CABINET_PAGE_PATH = '/cabinet'
export const ACTIVATION_PAGE_PATH = '/activation'
export const ADMIN_PAGE_PATH = '/admin'
export const ARTICLE_PAGE_PATH = '/article'
export const ARTICLE_EDIT_PAGE_PATH = '/article/edit'
export const ARTICLES_PAGE_PATH = '/articles'
export const HEALTH_ARTICLES_PAGE_PATH = '/articles/health'
export const HOBBY_ARTICLES_PAGE_PATH = '/articles/hobby'
export const JOB_ARTICLES_PAGE_PATH = '/articles/job'
export const CONSULTATION_PAGE_PATH = '/consultation'
export const NOT_FOUND_PAGE = '/404'

export const COOKIE_TOKEN = 'token'
