/// <reference types="react-scripts" />
declare module "@editorjs/code"
declare module "@editorjs/header"
declare module "@editorjs/quote"
declare module "@editorjs/simple-image"
declare module "@editorjs/nested-list"
declare module "@editorjs/checklist"
declare module "@editorjs/link"
declare module "@editorjs/table"
declare module "@editorjs/delimiter"
declare module "@editorjs/warning"
declare module "@editorjs/raw"
declare module "@editorjs/attaches"
declare module "@editorjs/marker"
